import { fetchAllMajors, fetchMajorById } from './firestore.js';
let majors = [];
const esc = v => String(v ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const local = (item, field, lang) => item?.[field]?.[lang] || item?.[field]?.en || '';
const state = (kind, text) => `<div class="state state--${kind}" role="status"><strong>${esc(text)}</strong></div>`;
function card(m, lang) { return `<article class="major-card"><div class="major-card__head"><h3>${esc(local(m,'name',lang))}</h3></div><p>${esc(local(m,'description',lang))}</p><div class="major-card__foot"><span class="tag">${esc(m.code || m.slug || m.id)}</span><a class="btn btn--ghost" href="major.html?id=${encodeURIComponent(m.id)}">${window.ICC_I18N.t('view_major',lang)} →</a></div></article>`; }
function renderLists() { const lang = window.ICC_I18N.getStoredLang(); document.querySelectorAll('[data-featured-majors],[data-majors-grid]').forEach(node => node.innerHTML = majors.length ? majors.map(m => card(m, lang)).join('') : state('empty', lang === 'ar' ? 'لا توجد تخصصات منشورة بعد.' : 'No majors have been published yet.')); }
async function loadLists() { if (!document.querySelector('[data-featured-majors],[data-majors-grid]')) return; try { majors = await fetchAllMajors(); renderLists(); } catch (e) { console.error(e); document.querySelectorAll('[data-featured-majors],[data-majors-grid]').forEach(node => node.innerHTML = state('error','Unable to load majors.')); } }
export function getMajorIdFromURL() { const p = new URLSearchParams(location.search); return p.get('id') || p.get('major'); }
function renderHeader(m) { const lang = window.ICC_I18N.getStoredLang(); document.querySelector('[data-major-name]').textContent = local(m,'name',lang); document.querySelector('[data-major-desc]').textContent = local(m,'description',lang); document.querySelector('[data-major-id]').textContent = m.code || m.slug || m.id; const img = document.querySelector('[data-curriculum-frame] img'); if (img && m.curriculumImageUrl) img.src = m.curriculumImageUrl; document.title = `${local(m,'name',lang)} — ICC`; }
async function loadHeader() { const mount = document.querySelector('[data-major-header]'), id = getMajorIdFromURL(); if (!mount) return; if (!id) { mount.innerHTML=state('error','A major was not selected.'); return; } try { const m = await fetchMajorById(id); if (!m) { mount.innerHTML=state('error','This major is unavailable.'); return; } window.ICC_CURRENT_MAJOR=m; renderHeader(m); document.dispatchEvent(new CustomEvent('icc:majorloaded',{detail:m})); } catch(e) { console.error(e); mount.innerHTML=state('error','Unable to load this major.'); } }
document.addEventListener('DOMContentLoaded',()=>{ loadLists(); loadHeader(); document.addEventListener('icc:languagechange',()=>{renderLists();if(window.ICC_CURRENT_MAJOR)renderHeader(window.ICC_CURRENT_MAJOR);}); });
