import { requireAdmin } from './admin-guard.js';
import { createAdminUser, deleteAdminUser, getAdminUsers, updateAdminUser } from '../../js/firestore.js';
const app=document.querySelector('[data-users-app]'),list=document.querySelector('[data-users-list]'),modal=document.querySelector('[data-modal]'),form=document.querySelector('[data-user-form]'),notice=document.querySelector('[data-notice]');let currentUser,users=[];
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));const say=(text,type='success')=>{notice.textContent=text;notice.className=`notice ${type}`;};
function render(){list.innerHTML=users.map(user=>`<tr><td><strong>${esc(user.displayName||'Unnamed user')}</strong><br><small>${esc(user.email||user.id)}</small></td><td>${user.role==='superadmin'?'Super admin':'Administrator'}</td><td>${(user.permissions||['Full access']).map(esc).join(', ')}</td><td><span class="status ${user.active?'':'off'}">${user.active?'Active':'Inactive'}</span></td><td class="actions"><button class="btn secondary" data-edit="${user.id}">Edit</button>${user.id!==currentUser.uid?`<button class="btn danger" data-delete="${user.id}">Remove</button>`:''}</td></tr>`).join('')||'<tr><td colspan="5">No user access profiles yet.</td></tr>';}
async function load(){users=await getAdminUsers();render();}function open(user={active:true,role:'admin',permissions:[]}){form.reset();form.uid.value=user.id||'';form.uid.readOnly=Boolean(user.id);form.displayName.value=user.displayName||'';form.email.value=user.email||'';form.role.value=user.role||'admin';form.active.value=String(user.active!==false);form.querySelectorAll('[name="permissions"]').forEach(box=>box.checked=(user.permissions||[]).includes(box.value));modal.hidden=false;}
requireAdmin(async profile=>{currentUser=profile;if(profile.role!=='superadmin'){app.innerHTML='<div class="state state--error"><strong>Only a Super administrator can manage team access.</strong></div>';app.hidden=false;return;}await load();app.hidden=false;});
document.querySelector('[data-add]').onclick=()=>open();document.addEventListener('click',async event=>{if(event.target.dataset.close)modal.hidden=true;const edit=event.target.dataset.edit,remove=event.target.dataset.delete;if(edit)open(users.find(user=>user.id===edit));if(remove){if(!confirm('Remove this user’s admin access? Their Firebase account will not be deleted.'))return;try{await deleteAdminUser(remove);say('Access removed.');await load();}catch(error){say(error.message,'error');}}});
form.addEventListener('submit',async event=>{event.preventDefault();const data=Object.fromEntries(new FormData(form));data.permissions=[...form.querySelectorAll('[name="permissions"]:checked')].map(x=>x.value);data.active=data.active==='true';const uid=data.uid;delete data.uid;try{if(form.uid.readOnly)await updateAdminUser(uid,data);else await createAdminUser(uid,data);modal.hidden=true;say('User access saved.');await load();}catch(error){console.error(error);say(error.message||'Could not save user access.','error');}});
